### ISSUE TITLE
Implementation of Dependency Properties

### ISSUE THREAD

**Issue by OpResCodes** [michaelosthege/LCARSToolkit#2]
Hi, first of all, great work with this control library!

I'm just wondering why you have implemented the setters in your dependency properties instead of using the property changed callbacks. With your implementation I wasn't able to set a style on the buttons for example. I changed it to a property changed callback function and got the style working.

Example in the button class:
![unchanged](https://user-images.githubusercontent.com/13434173/82739356-48512780-9d3f-11ea-9530-db7ebddef055.png)
I changed to this:
![changed](https://user-images.githubusercontent.com/13434173/82739361-5606ad00-9d3f-11ea-9337-22a05e11bdce.png)

**Comment by michaelosthege** [comment]
Hi, thanks!
At the time I simply didn't know how to do write a proper dependency property.
Feel free to open a pull request with the improvements!

Cheers
